[package]
name = "rkyv_test"
publish = false
description = "Test suite for rkyv crates"
version.workspace = true
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/rkyv"
repository = "https://github.com/rkyv/rkyv"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ptr_meta = { workspace = true, default-features = false }
rkyv = { workspace = true, default-features = false }
wasm-bindgen-test = { workspace = true, optional = true }
ahash = { version = "0.7" }

[features]
default = ["pointer_width_32", "little_endian", "strict", "std", "bytecheck"]

pointer_width_16 = ["rkyv/pointer_width_16"]
pointer_width_32 = ["rkyv/pointer_width_32"]
pointer_width_64 = ["rkyv/pointer_width_64"]

little_endian = ["rkyv/little_endian"]
big_endian = ["rkyv/big_endian"]

alloc = ["rkyv/alloc"]
bytecheck = ["rkyv/bytecheck"]
copy = ["rkyv/copy"]
copy_unsafe = ["rkyv/copy_unsafe"]
std = ["alloc", "rkyv/std"]
strict = ["rkyv/strict"]
wasm = ["wasm-bindgen-test"]
